In [1]:
import numpy as np

In [2]:
arr = []

In [3]:
n = int(input('enter number of elements in the array'))
print('enter elements one by one')
for i in range(n):
    x = int(input('enter the number'))
    arr.append(x)
print(arr)

enter number of elements in the array 3


enter elements one by one


enter the number 2
enter the number 3
enter the number 1


[2, 3, 1]


In [4]:
l = np.array(arr)
type(l)

numpy.ndarray

In [5]:
l

array([2, 3, 1])

In [6]:
s = sorted(l)

In [7]:
s

[1, 2, 3]

In [8]:
l

array([2, 3, 1])

In [9]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.ones(35)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1.])

In [11]:
np.full(5,5)

array([5, 5, 5, 5, 5])

In [12]:
np.arange(5,9)

array([5, 6, 7, 8])

In [13]:
np.arange(34,82,3)

array([34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64, 67, 70, 73, 76, 79])

In [14]:
np.random.rand(6)

array([0.7005859 , 0.52432094, 0.86667148, 0.25511441, 0.32457406,
       0.51976262])

In [15]:
np.random.randint(6, None, 100)

array([0, 1, 3, 4, 4, 1, 5, 1, 2, 3, 5, 5, 3, 0, 1, 2, 2, 1, 4, 1, 2, 5,
       3, 5, 1, 2, 4, 1, 1, 1, 3, 0, 4, 4, 2, 5, 4, 5, 1, 2, 5, 0, 2, 2,
       1, 0, 1, 5, 1, 0, 1, 3, 2, 4, 5, 4, 2, 0, 1, 5, 1, 3, 5, 0, 4, 1,
       0, 1, 5, 2, 1, 3, 5, 3, 4, 0, 0, 0, 2, 3, 4, 2, 3, 0, 5, 5, 1, 0,
       0, 5, 4, 0, 2, 3, 4, 1, 2, 4, 0, 0])

In [16]:
np.linspace(10,20,12,dtype = 'int32').reshape(3,4)

array([[10, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [17]:
a,step = np.linspace(10,55,10,dtype = 'int32',axis = -1,retstep = 'True')
print(a,step)

[10 15 20 25 30 35 40 45 50 55] 5.0


In [18]:
a.ndim #gives dimensions of the ndarray

1

In [19]:
a.nbytes #gives size of the ndarray in bytes

40

In [22]:
a.size #gives no. of elements or product of dimensions of the ndarray

10

In [23]:
a.data #gives memory address

In [24]:
a.dtype # gives data type of the ndarray since all the elements in a ndarray are of the same datatype

dtype('int32')

In [26]:
type(a)

numpy.ndarray

In [27]:
a.shape # gives shape of the array(rows and columns)

(10,)

In [62]:
demo = np.arange(9).reshape(3, 3)

In [63]:
demo

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [57]:
demo.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
demo.shape = (3,4)

In [58]:
demo

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
demo.shape

(3, 3)

In [69]:
print(demo[4,4]) # out of dimensions throws an error

IndexError: index 4 is out of bounds for axis 0 with size 3

In [49]:
demo[False]

array([], shape=(0, 3, 4), dtype=int32)

In [56]:
demo[]

SyntaxError: invalid syntax (<ipython-input-56-5d365ec02fa0>, line 1)